Class CoverActor : Interactable {
    override void Activate (Actor activator) {
        mass = 450;
        vel = (0,0,0);
        setStateLabel("Active");
        wake();
	}

    string flippedItemName;
    bool CanFlip;
    property CanFlip : CanFlip;
    default {
        +pushable;
        +UseSpecial;
        +shootable;
        +solid
    	-BloodSplatter
        +NOBLOODDECALS
	    PainThreshold 3;
        SelacoActor.UseTag "$INTERACT_FLIP";
        +SelacoActor.Crushable;
        DamageFactor "MeleeImpact", 0.1;
        Painchance 255;
        health 150;
        CoverActor.CanFlip true;
        PainChance "ExplosiveImpact", 255;
        PainChance "MeleeImpact", 256;
        BloodType "Stacked_Sparks_Lite", "Stacked_Sparks_Lite", "Stacked_Sparks_Lite";
        PainSound "impact/hardmetal";
        DamageFactor "MeleeImpactSplash", 5.0;
    	DamageFactor "BulletAlien", 5.0;
    }
    states {
        Active:
        Pain.ExplosiveImpact:
    	Pain.MeleeImpactSplash:
        Pain.MeleeImpact:
            TNT1 A 0 {
                bUseSpecial = false;
                ActivationType = THINGSPEC_DEFAULT;
            }
            TNT1 A 0 A_CHECKPROXIMITY("FlipOnSide", "Dawn", 600, 1, CPXF_SETTARGET);
        FlipOnSide:
            TNT1 A 0 A_PLAYSOUND("IMPACT/METALCOVERFLIP", CHAN_AUTO, 0.7, 0, 1.0, 0, frandom(0.95, 1.06));
            TNT1 A 0 A_FACETARGET();
            TNT1 A 0 A_SETANGLE(angle-90);
            VOXE LLLLLLLL 1 {
                bPreventSleep = true;
                bSlopeAlignment = false;
                vel = (0,0,0);
                bNoPain = true;
                A_SETROLL(roll + 5.5);
            }
            
            TNT1 A 0 A_SPAWNITEMEX(invoker.flippedItemName, 0, 5, 0);
            stop;
    }
}

Class FlippedCoverActor : CoverActor {
    default {
        SelacoActor.UseTag "$INTERACT_ROTATE";
        height 25;
        health 100;
        radius 23;
        mass 750;
        Pushfactor 0.2;
        DamageFactor "BulletAlien", 3.0;
    }
    States {
    	Pain.MeleeImpactSplash:
        Pain.MeleeImpact:
            TNT1 A 0 A_CHECKPROXIMITY("FlipOnSide", "Dawn", 600, 1, CPXF_SETTARGET);
        FlipOnSide:
            TNT1 A 0 A_FACETARGET();
            TNT1 A 0 A_SETANGLE(angle - 90);
            TNT1 A 0 A_SPAWNITEMEX(flippedItemName);
            stop;
         Pain:
            TNT1 A 0 A_Pain();
         Looper:
            VOXE L -1;
            loop;
    }
}