class Doodle : PaperActor {
    default {
        tag "$OBJECT_DRAWING";
		+SHOOTABLE
        -SOLID
        +NOPAIN
		DistanceCheck "r_ThingLODImportant";
        height 18;
        mass 100;
        height 25;
        selfLighting "";
        maxStepHeight 1;
        health 10;
        alpha 0.5;
        mass 10;
        scale 1.0;
        deathsound "dest/paper";
        Bloodtype "PaperChunk_UP", "PaperChunk_UP", "PaperChunk_UP";
        
        // Override calendars no-sleep behaviour as we are not animated
        -SELACOACTOR.WakeNearPlayer
        +SELACOACTOR.SleepWhenIdle
    }

	states
	{
		Precache:
			DRAW B 0;
			stop;
		Spawn:
		SpawnReal:
			DRAW B 1;
			TNT1 A 0 {
				A_SETROLL(random(-2,2));
				if (args[1] == 1) {
					A_SETROLL(0);
					bWallSprite = false;
					bFlatSprite = true;
				}
				if(args[0] == 0) {
					
					A_SpawnItemEx("PinSpawner", 0, frandom(-1,1), frandom(10.8,11.2));
				}
				SetStateLabel("DrawSprite");
			}
		DrawSprite:
			DRAW B 1 SleepIndefinite();
			stop;
		Pain.Shotgun:
		Pain.Explosiveimpact:
		Pain:
		Death.ExplosiveImpact:
		Death.Shotgun:
		Death: 
			TNT1 A 0 {
				Wake();
			}
			TNT1 AAA 0 A_SPAWNITEMEX("PaperDustEffect", frandom(0,50), frandom(-20,20), random(-10,10), frandom(0.3,0.6));
			TNT1 A 0 A_PlaySound("dest/paper");
			DRAW BBBBBBBBBBBBBBB 1 {
				bNoInteraction = true;
				a_fadeout(0.07);
				A_SETSCALE(scale.x+0.001, 0);
			}
			Stop;
	}    
}

class PatreonDoodle : Doodle {
	override void postBeginPlay() {
		super.postBeginPlay();
		SetTag(StringTable.localize("$OBJECT_DRAWING"));
	}
}
