#include "ACTORS/LEVELSPECIFIC/FBF_ELEVATOR_PANEL.zsc"

class PLANT1_TUBED : actor {
    override void tick() {
        super.tick();
        if(random(0,4) == 3) {
            A_SPAWNITEMEX("WaterBubble", frandom(-20, 20), frandom(-20, 20), frandom(-20, 50), 0, 0, frandom(0.5,1.2));
        }
    }

    default {
        +NOGRAVITY
        +NOINTERACTION
        scale 0.8;
    }
    states {
        Spawn:
            PLT1 B -1 BRIGHT;
            stop;
    }
}

class PLANT2_TUBED : PLANT1_TUBED {
    states {
        Spawn:
            PLT3 B -1 BRIGHT;
            stop;
    }
}

class PLANT3_TUBED : PLANT1_TUBED {
    states {
        Spawn:
            PLT9 B -1 BRIGHT;
            stop;
    }
}

class FogCloudShooter : actor {
    default {
        +NOINTERACTION;
    }
    States {
        Spawn:
            TNT1 A 0;
            TNT1 A 0 A_SpawnItemEx("FogSmokeFlorals", frandom(100, 750), frandom(-350, 350), frandom(-20,80), 0, frandom(1,2));
            stop;
    }
}

Class PlantPotPlantMachine : Plantpot {

    actor plantStamp;
    bool plantSuccess;

    override void tick()
    {
        super.tick();
        // Better to use Touch() for this.
        if(CheckProximity("HeavyBarrel", 30, 1, CPXF_CHECKSIGHT))
        {
            if(plantStamp)
            {
                plantStamp.destroy();
            }
            die(self, self);
        }
        if(plantStamp && plantStamp.master)
        {
            plantStamp.A_Warp(AAPTR_MASTER, 0, 0, 8, 0, WARPF_NOCHECKPOSITION|WARPF_INTERPOLATE);
        }
    }

    default
    {
        pushfactor 0.1;
        friction 0.1;	
        scale 1;

        // PROPERTIES
        mass 3;
        health 90000;
        DistanceCheck "r_ThingLOD";
        radius 5;
        speed 6;
        gravity 0.9;
        MaxStepHeight 6;
        height 20;
        pushfactor 0.8;

        SelacoActor.SleepDistance 512;
        +SelacoActor.WakeNearPlayer;
        Activation THINGSPEC_Default;
        -usespecial;
        +THRUACTORS;
        +NOBLOCKMAP;
    }
    
	states {
		Spawn:
			POTA A -1;
			loop;
		SpawnPlant:
			POTA A 0 
            {
                if(!plantStamp)
                {
                    [plantSuccess, plantStamp] = A_SPAWNITEMEX("Plant2DecorativeSmall", 0, 0, 8, 0, 0, 0, 0, SXF_SETMASTER);
                }
            }
			POTA A -1;
        DestroyPlant:
            TNT1 A 0
            {
                if(plantStamp)
                {
                    plantStamp.destroy();
                }
            }
            stop;
	}
}

class FogSmokeFlorals : actor {
    int frameID;
    default {
        +ROLLSPRITE;
        +NOINTERACTION;
        alpha 0;
        scale 0.7;
    }
    states {
        Spawn:
            SMK6 ABCD 0;
            TNT1 A 0;
            SMK6 A 0 {
                frameID = random(0,3);
            }
        FadeOut:
            SMK6 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 {
                frame = frameID;
                A_SETSCALE(scale.x + 0.002);
                A_SETROLL(roll+0.3);
                A_FADEIN(0.0025);
            }
            SMK6 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 {
                frame = frameID;
                A_SETROLL(roll+0.3);
                A_SETSCALE(scale.x + 0.002);
                A_FADEOUT(0.002);
            }
            stop;
    }
}

// PLANT MACHINE
class Plant2DecorativeSmall : actor
{

    override void tick()
    {
        super.tick();
        if(!master)
        {
            destroy();
        }
    }

    default
    {
        scale 0.7;
        radius 5;
        -SOLID
        +NOINTERACTION
        +WALLSPRITE
    }

	states 
    {
		spawn:
			PLT3 A -1;
			loop;
		Enlarge:
			PLT3 A -1;
			loop;
		Destroy:
			TNT1 A 0;
			stop;
	}
}

class FBF_DOORAMBUSH : SelacoActor
{
    actor zombieSpawn;
    bool succ;
    override void activate(actor activator)
    {
        setStateLabel("BreakDoor");
    }

    default
    {
        +BUDDHA
        +DONTTHRUST
        +SOLID;
        +NOCLIP
        radius 20;
        height 40;
        BloodType "Stacked_Sparks_Lite", "Stacked_Sparks_Lite", "Stacked_Sparks_Lite";
    }
    states
    {
        Spawn:
            VOXE L -1;
            stop;
        BreakDoor:
            TNT1 A 0;
            VOXE L 12
            {
                bPreventSleep = true;
                A_PLAYSOUND("SE06_DOORAMBUSH_1");
            }

            // Move door slightly.
            VOXE L 2
            {
                for(int x=0;x<8;x++)
                {
                    A_SpawnDefinedParticle("BulletImpactEffectMetalDefinition", frandom(8,12), frandom(-8,-16), frandom(10,72));
                }
                A_CHANGEVELOCITY(5,0,0, CVF_RELATIVE|CVF_REPLACE);
                A_SETANGLE(angle-5);
            }
            VOXE L 2
            {
                A_SETANGLE(angle+5);
                A_CHANGEVELOCITY(-5,0,0, CVF_RELATIVE|CVF_REPLACE);
            }
            VOXE L 1
            {
                A_SETANGLE(angle-5);
                A_CHANGEVELOCITY(0,0,0, CVF_RELATIVE|CVF_REPLACE);
            }
            VOXE L 25;
            VOXE L 0
            {
                A_PLAYSOUND("SE06_DOORAMBUSH_2");
            }
            VOXE L 15;
            // Spawn zombie
            VOXE L 1 
            {
                A_SETANGLE(angle+5);
                [succ, zombieSpawn] = A_SPAWNITEMEX("Zombie_grunt", -48, -48, 0,tid:args[0]);
                if(zombieSpawn)
                {
                    zombieSpawn.setStateLabel("GruntAmbush");
				//console.printf("Z tid: %i", zombieSpawn.tid);
                }
                for(int x=0;x<16;x++)
                {
                    A_SpawnDefinedParticle("BulletImpactEffectMetalDefinition", frandom(8,12), frandom(8,-64), frandom(10,72));
                }
            }
            TNT1 A 0
            {
                // Door pieces
                int yoffset = -48;
                A_SPAWNITEMEX("FBF_DOOR_PIECE_1", 25, 48+yoffset, 80, frandom(-3,3), frandom(0.5,1.5),  frandom(0,2), angle:90);
                A_SPAWNITEMEX("FBF_DOOR_PIECE_2", 25, 64+yoffset, 80, frandom(-3,3), frandom(1.5,2.5),  frandom(0,2), angle:90);
                A_SPAWNITEMEX("FBF_DOOR_PIECE_3", 25, 32+yoffset, 60, frandom(-3,3), frandom(4.5,5.5),  frandom(0,2), angle:90);
                A_SPAWNITEMEX("FBF_DOOR_PIECE_4", 25, 70+yoffset, 60, frandom(-3,3), frandom(6.5,8.5),  frandom(0,2), angle:90);
                A_SPAWNITEMEX("FBF_DOOR_PIECE_5", 45, 64+yoffset, 32, frandom(-3,3), frandom(9.5,10.5),  frandom(0,2), angle:90);
                A_SPAWNITEMEX("FBF_DOOR_PIECE_6", 45, 80+yoffset, 32, frandom(-3,3), frandom(11.5,12.5),  frandom(0,2), angle:90);
                A_SPAWNITEMEX("FBF_DOOR_PIECE_7", 45, 80+yoffset, 16, frandom(-3,3), frandom(13.5,15.5), frandom(0,2), angle:90);
                A_SPAWNITEMEX("FBF_DOOR_PIECE_8", 45, 16+yoffset, 12, frandom(-3,3), frandom(19.5,18.5), frandom(0,2), angle:90);
            }
            TNT1 A 0;
            stop;
    }
}

class FBF_DOOR_PIECE_1 : SelacoActorDecorationMissile { 
    override void postbeginPlay()
    {
        super.postbeginPlay();
        A_SETANGLE(angle+frandom(80,100));
        A_SETPITCH(90);
    }
    default
    {
        radius 2;
        BounceFactor 0.3;
        bounceCount 2;
    }
}
class FBF_DOOR_PIECE_2 : FBF_DOOR_PIECE_1 { }
class FBF_DOOR_PIECE_3 : FBF_DOOR_PIECE_1 { }
class FBF_DOOR_PIECE_4 : FBF_DOOR_PIECE_1 { }
class FBF_DOOR_PIECE_5 : FBF_DOOR_PIECE_1 { }
class FBF_DOOR_PIECE_6 : FBF_DOOR_PIECE_1 { }
class FBF_DOOR_PIECE_7 : FBF_DOOR_PIECE_1 { }
class FBF_DOOR_PIECE_8 : FBF_DOOR_PIECE_1 { }