class CardboardBasev2: PickupableDecoration {
	const CHUNK_VARIANT_AMOUNT = 3;
	const CHUNK_SPAWNS = 6;
	int chunkFrameOffset;
	enum CARDBOARD_COLOR {
		CARDBOARD_BROWN = 0,
		CARDBOARD_BROWN2 = 1,
		CARDBOARD_BLUE = 2,
		CARDBOARD_GREEN = 3,
	}

	override void beginPlay() {
		super.beginPlay();
		frameNum = random(0,CHUNK_VARIANT_AMOUNT);

		switch(frameNum) {
			case CARDBOARD_BROWN:
			case CARDBOARD_BROWN2:
				chunkFrameOffset = 0;
				break;
			case CARDBOARD_BLUE:
				chunkFrameOffset = 4;
				break;
			case CARDBOARD_GREEN:
				chunkFrameOffset = 8;
				break;
		}
	}

	Array<String> Chunks;
	default {
		+DOOMBOUNCE
		+DONTSPLASH
		+BOUNCEONFLOORS
		+SOLID
		+USEBOUNCESTATE
		+MOVEWITHSECTOR
		+SHOOTABLE
		+FLOORCLIP
		+CANPASS
		+BloodSplatter
		-NOBLOOD
		+SelacoActor.AllowRandomizerReplacement
		damagefactor "ExplosiveImpact", 50.0;
		damagefactor "magnumbullet", 10.0;
		damagefactor "BulletALien", 10.0;
		PainChance 255;
		height 13;
		health 40;
		BounceFactor 0.65;
		BounceCount 4;
		PushFactor 0.95;
		mass 300;
		MaxDropOffHeight 500;
		scale 1.0;
        BounceSound "impact/box";
		BloodType "Cardboard_Chunk", "Cardboard_Chunk", "Cardboard_Chunk";
		Tag "$OBJECT_CARDBOARDBOX";
		SelacoActor.UseTag "$ACT_GRAB";
		PickupableDecoration.grabsound "PICKUP/BOX";
		+SelacoActor.AllowGravityManipulation;
        +PickupableDecoration.TranslucentPickup;
		PickupableDecoration.landingSound "landing/cardboard";
		+SelacoActor.SpecialPushable;
		SelacoActor.SpecialPushFactor 0.96;
		-CANNOTPUSH;
	}
    
	override void tick() {
		super.tick();
		if(isMoving()) {
			A_PLAYSOUND("impact/boxmove", CHAN_5, 1.0, 1);
		}
		if (isStationary()) {
			A_StopSound(5);
		}
	}

	states {
		Spawn:
			VOXE L 0;
			VOXE L -1 {
				frame = frameNum;
			}
			loop;
        Inactive:
			VOXE L -1 {
				frame = frameNum;
			}
            loop;
		XDeath:
		Death.SniperBullet:
		Death.MagnumBullet:
		Death:
			TNT1 A 0 {
				for(int i=0;i<CHUNK_SPAWNS;i++) {
					actor chunkPiece;
					bool succ;
					[succ, chunkPiece] = A_SPAWNITEMEX("CardboardPieceMasterv2", frandom(-4,4), frandom(-4,4), 3, frandom(-3,3), frandom(-3,3), frandom(2,8));
					if(chunkPiece) {
						CardboardPieceMasterv2(chunkPiece).frameNum = chunkFrameOffset+random(0,3);
					}
				}
			}
			TNT1 AA 0 A_SPAWNITEMEX("PaperPieceUp");
			TNT1 AAAAA 0 {
				A_SPAWNITEMEX("Cardboard_Chunk", frandom(-20,20), frandom(-20,20),frandom(0,30));
			}
			TNT1 A 0 A_PLAYSOUND("dest/cardboardbreak", CHAN_AUTO, 1.0, 0, 0.7, 0, frandom(0.9,1.1));
			stop;
	}
}

class CardboardPieceMasterv2 : SelacoActor {
	mixin SleepDebugger;
	
	override void PostBeginPlay() {
		Super.PostBeginPlay();
		angle = (random(0,360));
		A_CHANGEVELOCITY(0, 0, frandom(2,4));
	}
	
	default {
		+Missile
		+INTERPOLATEANGLES
		+DOOMBOUNCE
		speed 5;
		radius 5;
		height 5;
		gravity 0.7;
		BounceFactor 0.4;
		BounceCount 3;
	}
	int frameNum;
	states {
		Spawn:
			VOXE L 1 {
				frame = frameNum;
				A_SETANGLE(angle+12);
				A_SETPITCH(pitch+12);
			}
			loop;
		Death:
            VOXE L 35 {
				frame = frameNum;
				A_SETPITCH(0);
			}
		WaitForFloor:
			VOXE L 2 {
				frame = frameNum;
				if(pos.z <= floorz && vel.length() < 0.001) {
					setStateLabel("RealDeath");
				}
			}
			loop;
		RealDeath:
			VOXE L 1 
			{
				frame = frameNum;
                if(getCvar("g_permanentDestruction"))
                {
                    sleepIndefinite();
                }
                else
                {
                    sleep(getCvar("cl_maxdecals"));
                }
            }
			VOXE LLLLLLLLLL 1 {
				frame = frameNum;
				A_FADEOUT(0.1);
			}
			stop;
	}
}

class GenericBox : CardboardBase
{
	default
	{
		radius 13;
	}
}

class GENERICBOX_PINK_A : GenericBox { }
class GENERICBOX_PINK_B : GenericBox { }
class GENERICBOX_SQUARE_A : GenericBox { }
class GENERICBOX_SQUARE_B : GenericBox { }
class GENERICBOX_SQUARE_C : GenericBox { }
class GENERICBOX_YELLOW_A : GenericBox { }
class GENERICBOX_YELLOW_B : GenericBox { }
class GENERICBOX_YELLOWTALL_A : GenericBox { }
class GENERICBOX_YELLOWTALL_B : GenericBox { }


// DEPRECATED. ONLY HERE FOR SAVE COMPATABILITY. DO NOT USE.
class CardboardBase : PickupableDecoration {
	Array<String> Chunks;
	default {
		+DOOMBOUNCE
		+DONTSPLASH
		+BOUNCEONFLOORS
		+SOLID
		+USEBOUNCESTATE
		+MOVEWITHSECTOR
		+SHOOTABLE
		+FLOORCLIP
		+CANPASS
		+BloodSplatter
		-NOBLOOD
		+SelacoActor.AllowRandomizerReplacement
		damagefactor "ExplosiveImpact", 50.0;
		damagefactor "magnumbullet", 10.0;
		damagefactor "BulletALien", 10.0;
		PainChance 255;
		height 13;
		health 40;
		BounceFactor 0.65;
		BounceCount 4;
		PushFactor 0.95;
		mass 300;
		MaxDropOffHeight 500;
		scale 1.0;
        BounceSound "impact/box";
		BloodType "Cardboard_Chunk", "Cardboard_Chunk", "Cardboard_Chunk";
		Tag "$OBJECT_CARDBOARDBOX";
		SelacoActor.UseTag "$ACT_GRAB";
		PickupableDecoration.grabsound "PICKUP/BOX";
		+SelacoActor.AllowGravityManipulation;
        +PickupableDecoration.TranslucentPickup;
		PickupableDecoration.landingSound "landing/cardboard";
		+SelacoActor.SpecialPushable;
		SelacoActor.SpecialPushFactor 0.96;
		-CANNOTPUSH;
	}
    
	override void tick() {
		super.tick();
		if(isMoving()) {
			A_PLAYSOUND("impact/boxmove", CHAN_5, 1.0, 1);
		}
		if (isStationary()) {
			A_StopSound(5);
		}
	}

	states {
		Spawn:
			VOXE L 0;
			VOXE L -1;
			loop;
        Inactive:
            VOXE L -1;
            loop;
		XDeath:
		Death.SniperBullet:
		Death.MagnumBullet:
		Death:
			TNT1 A 0 {
				for(int i=0;i<Chunks.size();i++) {
					A_SPAWNITEMEX(chunks[i], frandom(-4,4), frandom(-4,4), 3, frandom(-3,3), frandom(-3,3), frandom(2,8));
				}
			}
			TNT1 AA 0 A_SPAWNITEMEX("PaperPieceUp");
			TNT1 AAAAA 0 {
				A_SPAWNITEMEX("Cardboard_Chunk", frandom(-20,20), frandom(-20,20),frandom(0,30));
			}
			TNT1 A 0 A_PLAYSOUND("dest/cardboardbreak", CHAN_AUTO, 1.0, 0, 0.7, 0, frandom(0.9,1.1));
			stop;
	}
}

class CardboardBrown : CardboardBase {
	override void PostBeginPlay() {
		Super.PostBeginPlay();
		Chunks.push("Cardboard_piece_1_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_3_brown");
		Chunks.push("Cardboard_piece_4_brown");
	}
}

class CardboardBrown2 : CardboardBase {
	override void PostBeginPlay() {
		Super.PostBeginPlay();
		Chunks.push("Cardboard_piece_1_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_2_brown");
		Chunks.push("Cardboard_piece_3_brown");
		Chunks.push("Cardboard_piece_4_brown");
	}    
}

class CardboardBlue : CardboardBase {
	override void PostBeginPlay() {
		Super.PostBeginPlay();
		Chunks.push("Cardboard_piece_1_blue");
		Chunks.push("Cardboard_piece_2_blue");
		Chunks.push("Cardboard_piece_2_blue");
		Chunks.push("Cardboard_piece_2_blue");
		Chunks.push("Cardboard_piece_2_blue");
		Chunks.push("Cardboard_piece_3_blue");
		Chunks.push("Cardboard_piece_4_blue");
	}
}

class CardboardGreen : CardboardBase {
	override void PostBeginPlay() {
		Super.PostBeginPlay();
		Chunks.push("Cardboard_piece_1_Green");
		Chunks.push("Cardboard_piece_2_Green");
		Chunks.push("Cardboard_piece_2_Green");
		Chunks.push("Cardboard_piece_2_Green");
		Chunks.push("Cardboard_piece_2_Green");
		Chunks.push("Cardboard_piece_3_Green");
		Chunks.push("Cardboard_piece_4_Green");
	}
}

class CardboardSpawner : SelacoActor {
	static const String CardboardList[] =
		{
			"CardboardBrown",
			"CardboardBrown2",
			"CardboardBlue",
			"CardboardGreen"
	};		

	string CardboardToSpawn;

	override void PostBeginPlay() {
		CardboardToSpawn = CardboardList[random(0, CardboardList.size()-1)];
		super.PostBeginPlay();
	}


	default {
		+SelacoActor.preventSleep;
		+SelacoActor.AllowRandomizerReplacement	
    	scale 0.65;
	}

	states {
		spawn:
			TNT1 A 1;
			TNT1 A 0  {
				A_SpawnItemEx(CardboardToSpawn, flags:SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288, tid:tid);
			}
			stop;
	}
}


class Cardboard_piece_1_blue : CardboardPieceMaster { }
class Cardboard_piece_2_blue : CardboardPieceMaster { }
class Cardboard_piece_3_blue : CardboardPieceMaster { }
class Cardboard_piece_4_blue : CardboardPieceMaster { }

class Cardboard_piece_1_brown : CardboardPieceMaster { }
class Cardboard_piece_2_brown : CardboardPieceMaster { }
class Cardboard_piece_3_brown : CardboardPieceMaster { }
class Cardboard_piece_4_brown : CardboardPieceMaster { }

class Cardboard_piece_1_green : CardboardPieceMaster { }
class Cardboard_piece_2_green  : CardboardPieceMaster { }
class Cardboard_piece_3_green  : CardboardPieceMaster { }
class Cardboard_piece_4_green  : CardboardPieceMaster { }


class Cardboard_piece_1_Red : CardboardPieceMaster { }
class Cardboard_piece_2_Red  : CardboardPieceMaster { }
class Cardboard_piece_3_Red  : CardboardPieceMaster { }
class Cardboard_piece_4_Red  : CardboardPieceMaster { }

class CardboardPieceMaster : SelacoActor {
	mixin SleepDebugger;
	
	override void PostBeginPlay() {
		Super.PostBeginPlay();
		angle = (random(0,360));
		A_CHANGEVELOCITY(0, 0, 4);
	}
	
	default {
		+Missile
		+DOOMBOUNCE
		speed 5;
		radius 5;
		height 5;
		gravity 0.7;
		BounceFactor 0.4;
		BounceCount 3;
	}
	states {
		Spawn:
			VOXE L 2 {
				A_SETANGLE(angle+25);
				A_SETPITCH(pitch+25);
			}
			loop;
		Death:
            VOXE L 35 A_SETPITCH(0);
		WaitForFloor:
			VOXE L 2 {
				if(pos.z <= floorz && vel.length() < 0.001) {
					setStateLabel("RealDeath");
				}
			}
			loop;
		RealDeath:
			VOXE L 1 
			{
                if(getCvar("g_permanentDestruction"))
                {
                    sleepIndefinite();
                }
                else
                {
                    sleep(getCvar("cl_maxdecals"));
                }
            }
			VOXE LLLLLLLLLL 1 A_FADEOUT(0.1);
			stop;
	}
}
