// SELACO WILL PROVIDE YOU WITH THE BEST CHAIR-SHOOTING EXPERIENCE EVER. 

class PlasticChairBase : PickupableDecoration
{
    override void spawnLandingEffects() {
		A_SPAWNITEMEX("sparksnoflare", 10, 10 ,0, frandom(-0.07,0.07), frandom(-0.07,0.07));
		A_SPAWNITEMEX("sparksnoflare", -10, -10 ,0, frandom(-0.07,0.07), frandom(-0.07,0.07));
		A_SPAWNITEMEX("sparksnoflare", -10, 10 ,0,frandom(-0.07,0.07), frandom(-0.07,0.07));
		A_SPAWNITEMEX("sparksnoflare", 10,-10 ,0,frandom(-0.07,0.07), frandom(-0.07,0.07));
    }

    default {
        // FLAGS
		+UseSpecial
		-NOBLOOD
		+SOLID
		+SelacoActor.DecorativeActor;
		+SelacoActor.AllowGravityManipulation;
        // PROPERTIES
		BloodType "Stacked_Sparks_Lite", "Stacked_Sparks_Lite", "Stacked_Sparks_Lite";
		Tag "$OBJECT_PLASTICCHAIR";
		Activation THINGSPEC_Switch;
		PickupableDecoration.HoldHeight -17;
		SelacoActor.CollisionSound "COLLISION/TABLE";
		PickupableDecoration.LandingSound "random/metland";
		radius 14;
		height 27;
		PainChance 255;
		mass 200;
		Health 20;
		scale 1.06;
		PushFactor 0.8;
		+SLIDESONWALLS;
		-CANNOTPUSH;
		SelacoActor.SpecialPushFactor 0.95;
		+SelacoActor.SpecialPushable;
    }

}

class PlasticChair_Undamaged : PlasticChairBase {

	states {
        PickUp:
            TNT1 A 0 A_PLAYSOUND("PICKUP/CHAIR", CHAN_AUTO, 1.0, 0, 0.9, 0, frandom(0.9,1.1));
			goto Spawn;
        PutDown:
        Throw:
		ThrowLooper:
			VOXE L 1 {
				bThruActors = false;
			}
			VOXE L 1 {
				if(isTouchingSurface()) {
					spawnLandingEffects();
					A_Playsound(landingSound, CHAN_AUTO, 1.0, 0, 0.8, 0, frandom(0.9,1.1));
					setStateLabel("Spawn");
				}
			}
			loop;
        Active:
        Inactive:
		Spawn:
			VOXE L -1 {
				A_SetPitch(0);
			}
			stop;
		Pain:
			TNT1 A 0 A_SETANGLE(angle + random(3, 7));
			goto Spawn;
		Death:
			TNT1 A 0 A_SPAWNITEMEX("PlasticChair_damaged");
			TNT1 A 0 A_PlaySound("dest/PLSBRK",CHAN_AUTO, 0.75, 0, 1.0, false, 0.8);
			stop;
		Death.GravityThud:
		Death.MeleeImpactSplash:
		Death.explosiveimpact:
			TNT1 A 0 A_PlaySound("dest/PLSBRK",CHAN_AUTO, 0.75, 0, 1.0, false, 0.8);
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_1", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_2", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_3", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_4", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 A 0 A_SPAWNITEMEX("plasticchair_melted");
			TNT1 A 0 A_JumpIf(GetCVAR("r_ParticleIntensity")<=4, "Destroy");
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_1", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_2", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_3", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_4", frandom(10,46), random(-10, 10), random(0,360));
		Destroy:
		    TNT1 A 0;
			stop;
	}
}

class PlasticChair_damaged : PlasticChair_Undamaged  {
    default {
	    //category OminousDecoration
	    Tag "$OBJECT_PLASTICCHAIR_BROKEN";
    	Health 20;
    }
	states {
		Spawn:
			VOXE L random(40, 125);
			loop;
		Death.SniperBullet:
		Death.magnumbullet:
			TNT1 A 0 A_PlaySound("dest/PLSBRK",CHAN_AUTO, 1.0, 0, 1.0, false, 0.8);
			TNT1 A 0 A_SPAWNITEMEX("PlasticChair_broken1", 0, 0, 0, 0, 0, random(6,8));
			TNT1 A 0 A_SPAWNITEMEX("PlasticChair_broken2", 0, 0, 0, 0, 0, random(5,8));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_1", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_2", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_3", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_4", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 A 0 A_JumpIf(GetCVAR("r_ParticleIntensity")<=4, "Destroy");
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_1", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_2", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_3", frandom(10,46), random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_4", frandom(10,46), random(-10, 10), random(0,360));
			stop;
		Pain:
			TNT1 A 0 A_SETANGLE(angle + random(3, 7));
			goto Spawn;
		Destroy:
		    TNT1 A 0;
			Stop;
		Death:
			TNT1 A 0 A_PlaySound("dest/PLSBRK",CHAN_AUTO, 1.0, 0, 1.0, false, 0.8);
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_1", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_2", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_3", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_4", 32, random(-10, 10), random(0,360));
			TNT1 A 0 A_SPAWNITEMEX("plainchair_noplastic");
			TNT1 A 0 A_JumpIf(GetCVAR("r_ParticleIntensity")<=4, "Destroy");
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_1", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_2", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_3", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_4", 32, random(-10, 10), random(0,360));
			stop;
	}
}

class plainchair_noplastic : PlasticChair_Undamaged {
    default {
        //category OminousDecoration
        BloodType "Stacked_Sparks_Lite", "Stacked_Sparks_Lite", "Stacked_Sparks_Lite";
        Tag "$OBJECT_PLASTICCHAIR";
        damagefactor "Bullet", 0.9;
        Activation THINGSPEC_Activate;
        -NOBLOOD;
        +SOLID;
        health 80;
		SelacoActor.SpecialPushFactor 1;
    }
	states {
		Spawn:
			VOXE L random(40, 125);
			loop;
		Pain:
			TNT1 A 0 A_SETANGLE(angle + random(3, 7));
			goto Spawn;
		Death:
			TNT1 A 0 A_SPAWNITEMEX("PlasticChair_broken1", 0, 0, 0, 0, 0, frandom(6,8));
			TNT1 A 0 A_SPAWNITEMEX("PlasticChair_broken2", 0, 0, 0, 0, 0, frandom(5,8));
			stop;
	}
}

class PlasticChair_broken1 : SelacoActor {

    default {
        //category OminousDecoration
        Tag "$OBJECT_PLASTICCHAIR_BROKEN";
        +Missile;
        speed 3;
        scale 0.3;
        bounceCount 3;
        Bouncefactor 0.3;
        +doombounce;
        +USEBOUNCESTATE;
        +thruactors;
        -solid;
		-INTERPOLATEANGLES
		-SelacoActor.SlopeAlignment
		-SelacoActor.AllowGravityManipulation;
		+SelacoActor.DisallowGravityManipulation;
        gravity 0.7;
        painchance 0;
        Activation THINGSPEC_DEFAULT;
        mass 250;
        scale 1.06 ;
        Health 100;
    }
	states {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SETANGLE(random(0,360));
			TNT1 A 0 A_ChangeVelocity(frandom(-3.4, 3.4), frandom(-3.4, 3.4), frandom(1.3, 4), CVF_RELATIVE);
			goto Looper;
		Bounce:
			TNT1 A 0
			{
				for(int x=0;x<=2;x++) {
					A_SPAWNITEMEX("BodyImpactSmokeUltraTiny", 0, 0, 0, frandom(-0.2,0.2), frandom(-0.2,0.2), frandom(0.1,0.2));
				}
				EmitDefinition('ShortSpark360ParticleDefinition', chance: 0.75, numTries: 16, speed:frandom(2,5));
			}
			TNT1 A 0 A_PlaySound("bounce/metalfeet",CHAN_AUTO, 0.65, 0, 1.0, false, 0.9);
			goto Looper;
		Pain:
		Looper:
			CHAI GG 1 {
				if(vel.x == 0 && vel.y == 0 && vel.z == 0)
				{
					setStateLabel("Death");
				}
			}
			TNT1 A 0
			{
				A_SETPITCH(pitch + 25);
				//A_SETANGLE(angle + frandom(30,35));
			}
			loop;
		death:
			TNT1 A 0 A_PlaySound("bounce/metalfeet",CHAN_AUTO, 0.65, 0, 1.0, false, 0.9);
			TNT1 A 0 A_SETROLL(0);
			TNT1 A 0 A_SETPITCH(0);
			CHAI G -1;
			CHAI GGGGGGGGGG 1 A_FADEOUT(0.1);
			stop;
	}
}

class ComfyChair_damaged4a : PlasticChair_broken1 {
	states {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 {
				A_SETPITCH(90);
			}
			TNT1 A 0 A_ChangeVelocity(0, frandom(-5, -6.4), frandom(3.2, 5.3), CVF_RELATIVE);
			TNT1 A 0 setStateLabel("Looper");
		Looper:
			CHAI G 3 {
				A_SETROLL(roll+30);
				if(vel.x == 0 && vel.y == 0 && vel.z == 0)
				{
					setStateLabel("Death");
				}
			}
			loop;
	}
}
class ComfyChair_damaged4b : ComfyChair_damaged4a {
	states {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 {
				A_SETPITCH(90);
			}
			TNT1 A 0 A_ChangeVelocity(0, frandom(5, 6.4), frandom(3.2, 5.3), CVF_RELATIVE);
			TNT1 A 0 setStateLabel("Looper");
	}
}



class plasticchair_melted  : PlasticChair_broken1 {
    default {
        Tag "$OBJECT_PLASTICCHAIR_BROKEN";
        Activation THINGSPEC_DEFAULT;
        mass 250;
        scale 1.06;
        Health 100;
		radius 3;
		+SELACOACTOR.SleepWhenIdle;
		-SELACOACTOR.WakeNearPlayer;
		-SELACOACTOR.WakeOnTouch;
		-SELACOACTOR.WakeOnPain;
    }
	states {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SETANGLE(random(0,360));
			TNT1 A 0 A_ChangeVelocity(frandom(-6.4, 6.4), frandom(-6.4, 6.4), frandom(5.3, 15), CVF_REPLACE);
			goto Looper;
	}
}

class PlasticChair_broken2 : PlasticChair_broken1 {
    default {
        //category OminousDecoration;
        Activation THINGSPEC_DEFAULT;
        Tag "$OBJECT_PLASTICCHAIR_BROKEN";
        mass 250;
        scale 1.06;
		radius 3;
        Health 100;
    }
}

class PlasticChair_yellow_Undamaged : PlasticChair_Undamaged { 
	states {
		Death:
			TNT1 A 0 A_SPAWNITEMEX("PlasticChair_yellow_damaged");
			TNT1 A 0 A_PlaySound("dest/PLSBRK",CHAN_AUTO, 0.75, 0, 1.0, false, 0.8);
			stop;
		Death.explosiveimpact:
			TNT1 A 0 A_PlaySound("dest/PLSBRK",CHAN_AUTO, 0.75, 0, 1.0, false, 0.8);
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_1", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_2", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_3", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_4", 32, random(-10, 10), random(0,360));
			TNT1 A 0 A_SPAWNITEMEX("plasticchair_melted");
			TNT1 A 0 A_JumpIf(GetCVAR("r_ParticleIntensity")<=4, "Destroy");
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_1", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_2", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_3", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_4", 32, random(-10, 10), random(0,360));
			stop;
	}
}

class PlasticChair_yellow_damaged : PlasticChair_damaged { 
	states {
		Death.SniperBullet:
		Death.magnumbullet:
			TNT1 A 0 A_PlaySound("dest/PLSBRK",CHAN_AUTO, 1.0, 0, 1.0, false, 0.8);
			TNT1 A 0 A_SPAWNITEMEX("PlasticChair_broken1");
			TNT1 A 0 A_SPAWNITEMEX("PlasticChair_broken2");
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_1", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_2", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_3", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_4", 32, random(-10, 10), random(0,360));
			TNT1 A 0 A_JumpIf(GetCVAR("r_ParticleIntensity")<=4, "Destroy");
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_1", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_2", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_3", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_4", 32, random(-10, 10), random(0,360));
			stop;
		Death:
			TNT1 A 0 A_PlaySound("dest/PLSBRK",CHAN_AUTO, 1.0, 0, 1.0, false, 0.8);
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_1", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_2", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_3", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_4", 32, random(-10, 10), random(0,360));
			TNT1 A 0 A_SPAWNITEMEX("plainchair_noplastic");
			TNT1 A 0 A_JumpIf(GetCVAR("r_ParticleIntensity")<=4, "Destroy");
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_1", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_2", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_3", 32, random(-10, 10), random(0,360));
			TNT1 AA 0 A_SpawnProjectile("PlasticShard_yellow_4", 32, random(-10, 10), random(0,360));
			stop;
	}
}

class PlasticChair_Brown : PlasticChairBase
{

	bool damaged;
	string brokenPieceActor;
	property BrokenPieceActor : brokenPieceActor;

	override void postbeginPlay()
	{
		super.postbeginPlay();
		frameNum = 0;
	}

    override int takeSpecialDamage (Actor inflictor, Actor source, int damage, Name damagetype) {
        int res = Super.TakeSpecialDamage(inflictor, source, damage, damageType);
		if(health<= spawnHealth() && !damaged)
		{
			damaged = true;
			frameNum = 1;
		}
        return res;
    }

	default
	{
		PlasticChair_Brown.brokenPieceActor "PLASTICCHAIR_BROWN_PIECE_1";
		health 90;
	}

	states
	{
		Pain:
		Spawn:
			TNT1 A 0;
			VOXE A -1
			{
				frame = frameNum;
			}
			stop;
		Xdeath:
		Death:
			TNT1 A 0
			{
				A_SPAWNITEMEX("PaperDustEffect", 0, 0, 16, frandom(-0.5,0.5), frandom(-0.5,0.5), frandom(0.2,0.6));
				A_SPAWNITEMEX(brokenPieceActor, 0, 0, 0, frandom(2,5), 0, frandom(4,8), angle:random(0,360));
				A_SPAWNITEMEX("PLASTICCHAIR_GENERIC_PIECE_1", 0, 9, 0, 0, frandom(2,3), frandom(3,5), angle:random(-35,35));
				A_SPAWNITEMEX("PLASTICCHAIR_GENERIC_PIECE_2", 0, -9, 0, 0, frandom(-2,-3), frandom(3,5), angle:random(-35,35));
			}
			stop;
	}
}

class PlasticChair_Teal : PlasticChair_Brown { 
	default
	{
		PlasticChair_Brown.brokenPieceActor "PLASTICCHAIR_TEAL_PIECE_1";
	}
}

class PLASTICCHAIR_BROWN_PIECE_1 : SelacoActorDecorationMissile 
{
    override void bounceEffects()
    {
        for(int x=0;x<=2;x++) {
			A_SPAWNITEMEX("PaperDustEffect", 0, 0, 16, frandom(-0.5,0.5), frandom(-0.5,0.5), frandom(0.2,0.6));
        }
        A_SpawnDefinedParticle("BulletImpactEffectPlasticStationaryDefinition");
		A_PLAYSOUND("bounce/jug", CHAN_AUTO, pitch:1.35);
    }

    default {
        -SOLID;
        -PUSHABLE;
        +MISSILE;
        -SelacoActor.SlopeAlignment;
        +DoomBounce
        radius 3;
        gravity 0.8;
        SeeSound "";
        BounceFactor 0.5;
    }
}

class PLASTICCHAIR_TEAL_PIECE_1 : PLASTICCHAIR_BROWN_PIECE_1 { }

class PLASTICCHAIR_GENERIC_PIECE_1 : SelacoActorDecorationMissile { }
class PLASTICCHAIR_GENERIC_PIECE_2 : PLASTICCHAIR_GENERIC_PIECE_1 { }